#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands

$application->add(new \App\Command\CreateUserCommand());
$application->add(new \App\Command\UpdateUserCommand());
$application->add(new \App\Command\QueryUserCommand());
$application->add(new \App\Command\DeleteUserCommand());
$application->add(new \App\Command\RepairUserCommand());
$application->run();
